#!/bin/sh

# Lexer
bin/lexer > test/joos_tokens.txt
ret="$?"
case "$ret" in
    0) ;;
    42) exit 42; ;;
    *) echo "Exiting due to lexer error"; exit $ret; ;;
esac

# Parser
bin/parser > test/joos_tree.txt
ret="$?"
echo $ret
case "$ret" in
    0) ;;
    42) exit 42; ;;
    *) echo "Exiting due to parser error"; exit $ret; ;;
esac
echo $ret

# Weeder
bin/weeder
ret="$?"
case "$ret" in
    0) ;;
    42) exit 42; ;;
    *) echo "Exiting due to weeder error"; exit $ret; ;;
esac

# TODO: AST
