#!/bin/bash

HIGHLIGHT_BEGIN=$(tput setf 2)
HIGHLIGHT_END=$(tput sgr0)

# TODO: check for whitespace

# Check extensions.
for FILE; do
    echo "$FILE" | grep '\.java$'; ret="$?"
    if [ "$ret" != 0 ]; then
        echo "Invalid filename"
        exit 42
    fi
done

# Tokenize and parse files individually.
for FILE; do
    TOKENS="${FILE%.java}.tokens"
    PARSE="${FILE%.java}.parse"
    CLASSNAME="$(basename "$FILE" .java)"

    # Lexer
    bin/lexer "$FILE" > "$TOKENS"; ret="$?"
    case "$ret" in
        0) ;;
        42) exit 42; ;;
        *) echo "Exiting due to lexer error"; exit $ret; ;;
    esac

    # Parser
    bin/parser "$TOKENS" > "$PARSE"; ret="$?"
    case "$ret" in
        0) ;;
        42) exit 42; ;;
        *) echo "Exiting due to parser error"; exit $ret; ;;
    esac

    # Weeder
    bin/weeder "$CLASSNAME" "$FILE" "$TOKENS" "$PARSE"; ret="$?"
    case "$ret" in
        0) ;;
        42) exit 42; ;;
        *) echo "Exiting due to weeder error"; exit $ret; ;;
    esac
done

AST="test/ast.ast"

bin/compiler "$@" > "$AST"; ret="$?"
sed "/AstTaggedToken/ n; s/Ast.*/$HIGHLIGHT_BEGIN\\0$HIGHLIGHT_END/" "$AST"
# Print AST with AST nodes highlighted
case "$ret" in
    0) ;;
    42) exit 42; ;;
    *) echo "Exiting due to compiler error"; exit 42; ;; # TODO: should return $ret
esac
