#!/bin/bash

mkdir -p output
rm -f output/*

# Compile
./stdjoosc "$@"; ret=$?
case "$ret" in
    0) ;;
    42) exit 42; ;;
    *) echo "Exiting due to lexer error"; exit $ret; ;;
esac

# Assemble
for filename in $(echo output/*.s) test/stdlib/5.0/runtime.s; do
    test/nasm -O1 -f elf -g -F dwarf $filename
done

# Link
ld -melf_i386 -o output/main output/*.o

# Run
exec output/main
