#!/bin/bash

for FILE; do
    # Check extension.
    echo "$FILE" | grep '\.java$'; ret="$?"
    if [ "$ret" != 0 ]; then
        echo "Invalid filename"
        exit 42
    fi
done

for FILE; do
    TOKENS="${FILE%.java}.tokens"
    PARSE="${FILE%.java}.parse"

    # Lexer
    cp "$FILE" test/joos_input.txt
    bin/lexer > "$TOKENS"; ret="$?"
    cp "$TOKENS" test/joos_tokens.txt
    case "$ret" in
        0) ;;
        42) exit 42; ;;
        *) echo "Exiting due to lexer error"; exit $ret; ;;
    esac

    # Parser
    bin/parser > "$PARSE"; ret="$?"
    cp "$PARSE" test/joos_parse.txt
    case "$ret" in
        0) ;;
        42) exit 42; ;;
        *) echo "Exiting due to parser error"; exit $ret; ;;
    esac

    # Weeder
    echo -n "$(basename "$FILE" .java)" > test/joos_classname.txt
    bin/weeder; ret="$?"
    case "$ret" in
        0) ;;
        42) exit 42; ;;
        *) echo "Exiting due to weeder error"; exit $ret; ;;
    esac
done

# TODO: AST
