#!/bin/sh

# Lexer
bin/lexer > test/joos_tokens.txt
if [ "$?" != 0 ]; then
    exit 42
fi

# Parser
bin/parser > test/joos_tree.txt
if [ "$?" != 0 ]; then
    exit 42
fi

# Weeder
bin/weeder
if [ "$?" != 0 ]; then
    exit 42
fi

# TODO: AST
